version: 2
jobs:
  test:
    working_directory: ~/vtypes
    docker:
      - image: circleci/node:6.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run bootstrap
      - run: npm run clean
      - run: npm run build
      - run: npm run coverage
      - run: npm run lint
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  test:
    jobs:
      - test
